os:
  - Visual Studio 2015
clone_folder: C:\TBuild\tdesktop
test: off
deploy: off
configuration: Release
platform: Any CPU

environment:
  matrix:
    - GENERATOR: "Visual Studio 9 2008"
      UNICODE: ON
    - GENERATOR: "Visual Studio 9 2008"
      UNICODE: OFF
    - GENERATOR: "Visual Studio 10 2010"
      UNICODE: ON
    - GENERATOR: "Visual Studio 10 2010"
      UNICODE: OFF
    - GENERATOR: "Visual Studio 11 2012"
      UNICODE: ON
    - GENERATOR: "Visual Studio 11 2012"
      UNICODE: OFF
    - GENERATOR: "Visual Studio 12 2013"
      UNICODE: ON
    - GENERATOR: "Visual Studio 12 2013"
      UNICODE: OFF
    - GENERATOR: "Visual Studio 14 2015"
      UNICODE: ON
    - GENERATOR: "Visual Studio 14 2015"
      UNICODE: OFF     
matrix:
  allow_failures:
    #Group: (EXPERIMENTAL / SUPPORTED)
    #EXPERIMENTAL is allowed to fail under the build matrix
    - GROUP: "EXPERIMENTAL"


build:
  project: qttabbar\QTTabBar Rebirth.sln
  verbosity: minimal

artifacts:
  - path: qttabbar\Installer\bin\Release\zh-CN\QTTabBar Setup.msi
    name: QTTabBar Setup_zh-CN.msi
  - path: qttabbar\Installer\bin\Release\en-US\QTTabBar Setup.msi
    name: QTTabBar Setup_en-US.msi
