image: Visual Studio 2013
clone_folder: C:\TBuild\tdesktop
test: off
deploy: off
configuration: Release
platform: Any CPU

environment:
  matrix:
    - GENERATOR: "Visual Studio 10 2010"
      UNICODE: ON
    - GENERATOR: "Visual Studio 10 2010"
      UNICODE: OFF
      
matrix:
  fast_finish: true

build:
  project: qttabbar\QTTabBar Rebirth.sln
  verbosity: minimal

artifacts:
  - path: qttabbar\Installer\bin\Release\zh-CN\QTTabBar Setup.msi
    name: QTTabBar Setup_zh-CN.msi
  - path: qttabbar\Installer\bin\Release\en-US\QTTabBar Setup.msi
    name: QTTabBar Setup_en-US.msi
