os: Visual Studio 2015
clone_folder: C:\TBuild\
test: off
deploy: off
configuration: Release
platform: Any CPU

environment:
  GTEST_REPEAT: 1

  matrix:
  - VldStackWalkMethod: safe
    Toolset: v90
    Solution: qttabbar\QTTabBar Rebirth.sln
    GTEST_FILTER: -*.Mfc*
  - VldStackWalkMethod: safe
    Toolset: v100
    Solution: qttabbar\QTTabBar Rebirth.sln
    GTEST_FILTER: -*.Mfc*
  - VldStackWalkMethod: safe
    Toolset: v110
    Solution: qttabbar\QTTabBar Rebirth.sln
    GTEST_FILTER: -*.Mfc*
  - VldStackWalkMethod: safe
    Toolset: v120_xp
    Solution: qttabbar\QTTabBar Rebirth.sln
  - VldStackWalkMethod: safe
    Toolset: v140_xp
    Solution: qttabbar\QTTabBar Rebirth.sln

  - VldStackWalkMethod: fast
    Toolset: v90
    Solution: qttabbar\QTTabBar Rebirth.sln
    GTEST_FILTER: -*.Mfc*
  - VldStackWalkMethod: fast
    Toolset: v100
    Solution: qttabbar\QTTabBar Rebirth.sln
    GTEST_FILTER: -*.Mfc*
  - VldStackWalkMethod: fast
    Toolset: v110
    Solution: qttabbar\QTTabBar Rebirth.sln
    GTEST_FILTER: -*.Mfc*
  - VldStackWalkMethod: fast
    Toolset: v120_xp
    Solution: qttabbar\QTTabBar Rebirth.sln
  - VldStackWalkMethod: fast
    Toolset: v140_xp
    Solution: qttabbar\QTTabBar Rebirth.sln
    
matrix:
  fast_finish: false
    


build:
- ps: |
    Write-Output "Configuration: $env:CONFIGURATION"
    Write-Output "Platform: $env:PLATFORM"
    msbuild /v:m /p:"Configuration=$env:CONFIGURATION" /p:Platform="$env:PLATFORM" "$env:Solution" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"


artifacts:
  - path: qttabbar\Installer\bin\Release\zh-CN\QTTabBar Setup.msi
    name: QTTabBar Setup_zh-CN.msi
  - path: qttabbar\Installer\bin\Release\en-US\QTTabBar Setup.msi
    name: QTTabBar Setup_en-US.msi
